config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  root "home#home"

  resources :time_tracks
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/time_track.rb
class TimeTrack < ApplicationRecord
  belongs_to :user
  validate :check_start_and_end
  
  def check_start_and_end
    if time_started > time_ended
      errors.add(:time_started, 'must be smaller than end date')
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :time_tracks
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:name, :email, :password)}
    devise_parameter_sanitizer.permit(:account_update) { |u| u.permit(:name, :email, :password, :current_password)}
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def home
  end
end  

app/controllers/time_tracks_controller.rb
class TimeTracksController < ApplicationController
  before_action :set_time_track, only: %i[ edit update destroy ]

  def index
    if current_user.is_admin?
      @q = TimeTrack.ransack(params[:q])
      @time_tracks = @q.result(distinct: true)
      respond_to do |format|
        format.html
        format.js
      end
    else
      @q = current_user.time_tracks.ransack(params[:q])
      @time_tracks = @q.result(distinct: true)
      respond_to do |format|
        format.html
        format.js
      end
    end
      
  end

  def edit
    respond_to do |format|
      format.js
    end
  end

  def new
    @time_track = TimeTrack.new
    respond_to do |format|
      format.js
    end
  end

  def update
    respond_to do |format|
      if @time_track.update(time_track_params)
        format.js
        format.json { render :show, status: :ok, location: @time_track }
      else
        format.js
        format.json { render json: @time_track.errors, status: :unprocessable_entity }
      end
    end
  end

  def create
    @time_track = current_user.time_tracks.new(time_track_params)

    respond_to do |format|
      if @time_track.save
        format.js
        format.json { render :show, status: :created, location: @time_track }
      else
        format.js
        format.json { render json: @time_track.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @time_track.destroy
    
    respond_to do |format|
      format.html { redirect_to time_tracks_url, notice: "Time track was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private

  def set_time_track
    @time_track = TimeTrack.find(params[:id])
  end

  def time_track_params
    params.require(:time_track).permit(:time_started, :time_ended, :description, :time_type, :user_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/home/home.html.haml
%div{:style => "width: 100%; text-align: center;"}
  = image_tag "Logo34-01.png", size: "500x500"
.row
  %h1{:style => "text-align: center;"} TimeTracker

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title TimeTracker
    %meta{:content => "width=device-width,initial-scale=1", :name => "viewport"}/
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'
  %body{:style => "background-color: rgba(145, 147, 148, 0.247);"}
    .container{:style => "background-color: white; height: 100vh"}
      .container
        %header.d-flex.flex-wrap.align-items-center.justify-content-center.justify-content-md-between.py-3.mb-4.border-bottom
          %a.d-flex.align-items-center.col-md-3.mb-2.mb-md-0.text-dark.text-decoration-none{:href => "/"}
            %svg.bi.me-2{"aria-label" => "Bootstrap", :height => "32", :role => "img", :width => "40"}
              %use{"xlink:href" => "#bootstrap"}
          %ul.nav.col-12.col-md-auto.mb-2.justify-content-center.mb-md-0
            %li= link_to "Home", root_path, class: "nav-link px-2 link-secondary"
            %li= link_to "Time Tracks", time_tracks_path, class: "nav-link px-2 link-secondary"
          .col-md-3.text-end
            - if user_signed_in?
              = current_user.email
              = link_to "Sign Out", destroy_user_session_path, method: :delete, class: "btn btn-primary", style: "margin-left: 10px;"
            - else
              = link_to "Login", new_user_session_path, class:"btn btn-outline-primary me-2"
              = link_to "Sign Up", new_user_registration_path, class: "btn btn-primary"
      = yield
    #formModal.modal.fade{"aria-hidden" => "true", "aria-labelledby" => "exampleModalLabel", :tabindex => "-1"}
      .modal-dialog.modal-lg
        .modal-content

app/views/time_tracks/_errors.html.haml
#error_explanation
  %h6
    = pluralize(time_track.errors.count, "error")
    prohibited this time_track from being saved:
    %ul
      - time_track.errors.each do |error|
        %li{:style => "color: red;"}= error.full_message.humanize

app/views/time_tracks/_filters.html.haml
= search_form_for @q, remote: true do |f|
  .row
    .col-3
      .input-group
        = f.datetime_field :time_started_gt, class: "form-control search-item"
    .col-3
      .input-group
        = f.datetime_field :time_started_lt, class: "form-control search-item"
    .col-3
      .input-group
        = f.datetime_field :time_ended_gt, class: "form-control search-item"
    .col-3
      .input-group
        = f.datetime_field :time_ended_lt, class: "form-control search-item"
  %hr/
  .row
    .col-3
    .col-3
      .input-group
        = f.search_field :time_type_cont, class: "form-control search-item", placeholder: "Time Type"
    .col-3
      .input-group
        = f.search_field :description_cont, class: "form-control search-item", placeholder: "Description"
  - if current_user.is_admin?
    %hr/
    .row
      .col-12{:style => "text-align: center;"}
        = f.select :user_name_cont, options_for_select(User.pluck(:name)), class: "form-select search-item", include_blank: "User's Name"
  %br/
  .row
    .col-12{:style => "text-align: right;"}
      %a#clean-button.btn.btn-info Clean Filters
      = f.submit "Search", class: "btn btn-secondary", id: "submit"
:javascript
  $("select").addClass("form-select")
  $('#clean-button').on("click",function(){
    $(".search-item").val('');
    $('#submit').click();
  })

app/views/time_tracks/_form.html.haml
.modal-header
  %h5#exampleModalLabel.modal-title
    = params[:action].titleize
    Time Track
  %button.btn-close{"aria-label" => "Close", "data-bs-dismiss" => "modal", :type => "button"}
.modal-body
  = form_with(model: time_track, data: {remote: true}) do |form|
    #errors
      - if time_track.errors.any?
        = render 'errors', time_track: time_track
    .container
      .input-group.row
        = form.label :time_type, class: "col-2"
        = form.text_field :time_type, {class: 'form-control col-6', style: "width: 60%;"}
    %br/
    .container
      .input-group.row
        = form.label :time_started, class: "col-2"
        = form.datetime_select :time_started, {class: 'form-control datepicker col-6', style: "width: 60%;"}
    %br/
    .container
      .input-group.row
        = form.label :time_ended, class: "col-2"
        = form.datetime_select :time_ended, {class: 'form-control datepicker col-6', style: "width: 60%;"}
    %br/
    .container
      .input-group.row
        = form.label :description, class: "col-2"
        = form.text_area :description, {class: 'form-control col-9', style: "width: 60%;"}
    %br/
    .actions{:style => "text-align: center;"}
      = form.submit class: 'btn btn-primary'

app/views/time_tracks/_list.html.haml
%table.col-10.table.table-hover{:style => "text-align: center;"}
  %thead
    %tr
      - if current_user.is_admin?
        %th Username
      %th Time Started
      %th Time Ended
      %th Type
      %th Description
      %th{:colspan => "2"} Actions
  %tbody
    - time_tracks.each do |time_track|
      %tr
        - if current_user.is_admin?
          %td= time_track.try(:user).try(:name)
        %td= time_track.time_started.strftime("%d.%m.%Y %H:%M")
        %td= time_track.time_ended.strftime("%d.%m.%Y %H:%M")
        %td= time_track.time_type
        %td= time_track.description
        %td
          = link_to 'Edit', edit_time_track_path(time_track), remote: true, class: "btn btn-warning btn-sm"
        %td= link_to 'Destroy', time_track, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger btn-sm"

app/views/time_tracks/_update.js.haml
- if time_track.errors.any?
  $('#errors').html("#{j (render 'errors', time_track: time_track)}")
- else
  $('#formModal').modal('hide');
  $('#table').html("#{j (render 'list', time_tracks: current_user.is_admin? ? TimeTrack.all : current_user.time_tracks )}")

app/views/time_tracks/create.js.haml
= render 'update', format: :js, time_track: @time_track

app/views/time_tracks/edit.js.haml
$('#formModal').find(".modal-content").html("#{j (render 'form', time_track: @time_track )}")
$('#formModal').modal('toggle');
$('#formModal').modal('show');
$('select').addClass('form-control')

app/views/time_tracks/index.html.haml
%p#notice= notice
%br/
%br/
#filters{:style => "margin: 20px;"}
  = render "filters"
.container{:style => "text-align: right; padding-right: 10px;"}
  = link_to "New Time Track", new_time_track_path, remote:true, class: "btn btn-primary"
  #table{:style => "padding-top: 20px;"}
    = render "list", time_tracks: @time_tracks

app/views/time_tracks/index.js.haml
$('#table').html("#{j (render 'list', time_tracks: @time_tracks )}")

app/views/time_tracks/new.js.erb
$('#formModal').find(".modal-content").html("<%= j (render 'form', time_track: @time_track )%>")
$('#formModal').modal('toggle');
$('#formModal').modal('show');
$('select').addClass('form-control')

app/views/time_tracks/new.js.haml
$('#formModal').find(".modal-content").html("#{j (render 'form', time_track: @time_track )}")
$('#formModal').modal('toggle');
$('#formModal').modal('show');
$('select').addClass('form-control')

app/views/time_tracks/update.js.haml
= render 'update', format: 'js', time_track: @time_track